export const events = [
  {
    image: '/images/event1.png',
    title: 'KubeCon + CloudNativeCon Europe 2026',
    slug: 'kubecon-europe-2026',
    date: 'Mar 23-26, 2026',
    time: '09:00 AM',
    location: 'Amsterdam, Netherlands',
  },
  {
    image: '/images/event2.png',
    title: 'PyCon US 2026',
    slug: 'pycon-us-2026',
    date: 'May 13-19, 2026',
    time: '08:30 AM',
    location: 'Long Beach, California, USA',
  },
  {
    image: '/images/event3.png',
    title: 'PyCon DE & PyData 2026',
    slug: 'pycon-de-pydata-2026',
    date: 'Apr 14-17, 2026',
    time: '09:30 AM',
    location: 'Darmstadt, Germany',
  },
  {
    image: '/images/event4.png',
    title: 'PyCon AU 2026',
    slug: 'pycon-au-2026',
    date: 'Aug 26-30, 2026',
    time: '08:00 AM',
    location: 'Brisbane, Australia',
  },
  {
    image: '/images/event5.png',
    title: 'DEF CON Training Las Vegas 2026',
    slug: 'def-con-training-las-vegas-2026',
    date: 'Aug 8-11, 2026',
    time: '09:00 AM',
    location: 'Las Vegas, Nevada, USA',
  },
  {
    image: '/images/event6.png',
    title: 'PyCon Estonia 2026',
    slug: 'pycon-estonia-2026',
    date: 'Oct 8-9, 2026',
    time: '10:00 AM',
    location: 'Tallinn, Estonia',
  },
  {
    image: '/images/event-full.png',
    title: 'PyCon Wroclaw 2026',
    slug: 'pycon-wroclaw-2026',
    date: 'Nov 20-21, 2026',
    time: '09:30 AM',
    location: 'Wroclaw, Poland',
  },
];
